### ISSUE TITLE
How to request a higher transaction limit on AlchemyAPI key?

### ISSUE THREAD

**Issue by ibmalan** [watson-developer-cloud/social-customer-care#12]
See step 3 of the Getting Started section for information about requesting a higher transaction limit on your sample AlchemyAPI key.  but I didn't see any description in step 3.

**Comment by andrewfayres** [comment]
I'll update the readme.

The alchemy plans were changed during the course of writing and the old process of having to get a higher limit key is no longer required. It now works like the rest of the services so that you set the plan when creating the service instance. So when creating the alchemy service you can create it with the `standard` plan instead of the `free` plan. The standard plan does have a cost associated with it.

**Comment by germanattanasio** [comment]
http://alchemyapi.mybluemix.us/ibmer-key.html
