### ISSUE TITLE
Create updated version of pattern with Natural Language Classifier 

### ISSUE THREAD

**Issue by jacalcat** [watson-developer-cloud/social-customer-care#22]
I'm having a difficult time finding good examples. This one looks perfect but is a bit old. A new demo or an updated version of this one would be very helpful.

**Comment by jeff-arn** [comment]
This is being closed as this repo has been deprecated. If you had a question that arose through this issue that has not been answered, we recommend that you ask on Stack Overflow with the IBM Watson tag, or on IBM DeveloperWorks Answers with the tag WATSON

--

@jacalcat for your specific question, you might want to check out the [Natural Language Classifier Demo](https://github.com/watson-developer-cloud/natural-language-classifier-nodejs). Hopefully this is helpful, and apologies that this issue was not addressed in a timely manner.
